name: Build branch

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 1.21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Compile with Maven
      run: mvn -B compile --file pom.xml

    - name: Run tests with Maven
      run: mvn -B test --file pom.xml
      # TODO Add tests again.
      # TODO Build site...
